scene: scene0000_00
inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0000.yaml
data:
  input_folder: /home/esandstroem/scratch-second/data/scannet/scene0000_00
  output: output/ScanNet/scene0000