scene: scene0169_00
inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0169.yaml
data:
  input_folder: /home/esandstroem/scratch-second/data/scannet/scene0169_00
  output: output/ScanNet/scene0169
cam: 
  fx: 574.540771
  fy: 577.583740
  cx: 322.522827
  cy: 238.558853