scene: scene0103_00
inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0103.yaml
data:
  input_folder: /home/esandstroem/scratch-second/data/scannet/scene0103_00
  output: output/ScanNet/scene0103
cam: 
  fx: 577.870605
  fy: 577.870605
  cx: 319.500000
  cy: 239.500000