scene: scene0059_00
inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0059.yaml
data:
  input_folder: /home/esandstroem/scratch-second/data/scannet/scene0059_00
  output: output/ScanNet/scene0059